### ISSUE TITLE
Should tsup be a dev dependency?

### ISSUE THREAD

**Issue by boehs** [zuramai/starback.js#13]
Hi, I noticed that there is about 100 dependencies pulled in due to `tsup`, despite the fact that `dist` has no dependency on it. I suspect it snuck into the normal dependencies instead of dev somehow. Thank you!

**Comment by zuramai** [comment]
Yes you're right. Would you make a pull request to fix it?

**Comment by boehs** [comment]
done! checkout the linked pr ❤️

**Comment by zuramai** [comment]
Thank you!

**Comment by boehs** [comment]
Is there chance you could publish the new version?

**Comment by ditpowuh** [comment]
Hey, just as a heads-up that the change with tsup has not been published yet - so it's still showing up as a dependency in the current release.
